services:
    laravel:        
        image: ghcr.io/francoisjun/ame-app:latest
        container_name: ame-app
        ports:
            - '${APP_PORT:-8000}:80'
        env_file:
            - .env
        depends_on:
            - mysql
            
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: ame-db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'ame-db:/var/lib/mysql'
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    default:
        name: ame-network

volumes:
    ame-db:
        driver: local
